version: '3.5'

services:
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - blog
    restart: unless-stopped
  
  blogapi:
    container_name: blogapi
    ports:
        - 5555:80
    build: .
    links:
        - postgres
    depends_on:
        - "postgres"
    networks:
        - blog

volumes:
  postgres:
  pgadmin:

networks:
  blog:
    driver: bridge